version: '3'

services:
  vpn:
    cap_add:
      - NET_ADMIN
    container_name: vpn
    dns:
      - 5.101.137.251
      - 46.165.222.246
    environment:
      CRYPTOSTORM_USERNAME: [...]
      CRYPTOSTORM_CONFIG_FILE: [...]
    image: microbug/cryptostorm-client:latest
    networks:
      default:
        ipv4_address:
          192.168.0.4

  deluge:
    container_name: deluge
    depends_on:
      - vpn
    environment:
      TZ: Europe/London
      PGID: 1000
      PUID:  1000
    image: linuxserver/deluge:latest
    network_mode: "service:vpn"
    volumes:
      - /services-data/deluge/config:/config
      - /services-data/deluge/downloads:/downloads  

networks:
  default:
    external:
      name: external-network
